
CREATE TABLE list_item (id BIGINT NOT NULL, date_created TIMESTAMP WITHOUT TIME ZONE, date_updated TIMESTAMP WITHOUT TIME ZONE, content VARCHAR(255), note_id BIGINT NOT NULL, CONSTRAINT list_item_pkey PRIMARY KEY (id));

CREATE TABLE application_user (id BIGINT NOT NULL, date_created TIMESTAMP WITHOUT TIME ZONE, date_updated TIMESTAMP WITHOUT TIME ZONE, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, CONSTRAINT application_user_pkey PRIMARY KEY (id));

CREATE TABLE note (id BIGINT NOT NULL, date_created TIMESTAMP WITHOUT TIME ZONE, date_updated TIMESTAMP WITHOUT TIME ZONE, heading VARCHAR(255) NOT NULL, note_type VARCHAR(255) NOT NULL, shared BOOLEAN NOT NULL, author_id BIGINT NOT NULL, folder_id BIGINT, CONSTRAINT note_pkey PRIMARY KEY (id));

CREATE TABLE folder (id BIGINT NOT NULL, date_created TIMESTAMP WITHOUT TIME ZONE, date_updated TIMESTAMP WITHOUT TIME ZONE, name VARCHAR(255) NOT NULL, owner_id BIGINT, CONSTRAINT folder_pkey PRIMARY KEY (id));

ALTER TABLE note ADD CONSTRAINT fk_note_to_application_user FOREIGN KEY (author_id) REFERENCES application_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE folder ADD CONSTRAINT fk_folder_to_application_user FOREIGN KEY (owner_id) REFERENCES application_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE application_user ADD CONSTRAINT uk_application_user_username UNIQUE (username);

ALTER TABLE folder ADD CONSTRAINT uk_folder_name UNIQUE (name);

ALTER TABLE list_item ADD CONSTRAINT fk_list_item_to_note FOREIGN KEY (note_id) REFERENCES note (id) ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE note ADD CONSTRAINT note_folder_to_folder FOREIGN KEY (folder_id) REFERENCES folder (id) ON UPDATE NO ACTION ON DELETE NO ACTION;


CREATE SEQUENCE  IF NOT EXISTS hibernate_sequence AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

